GET http://localhost:3000/api/members/sales

###
POST http://localhost:3000/api/members 
Content-Type:application/json

{
    "id": 11,
    "name": "chacha",
    "team": "engineering",
    "position": "Server Developer",
    "emailAddress": "chacha@google.com",
    "phoneNumber": "0110-xxxx-xxxx",
    "admissionDate": "2018/12/10",
    "birthday": "1994/11/08",
    "profileImage": "profile11.png"
}
###
DELETE http://localhost:3000/api/members/2